on:
  workflow_call:

name: 'Tests'

jobs:
  tests:
    name: 'Pull Request Checks'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out the repo'
        uses: actions/checkout@v3

      - name: 'Install Node.js'
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16

      - name: 'Install the dependencies'
        run: npm ci --no-audit

      - name: 'Lint the code'
        run: npm run lint

      - name: 'Add lint summary'
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: 'Run tests'
        run: npm run test

      - name: 'Test run build'
        run: npm run build

      - name: 'Add test summary'
        run: |
          echo "## Build results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
